"""criar tabelas

Revision ID: aa44840755b7
Revises: 
Create Date: 2026-03-15 20:04:48.524530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa44840755b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deteccoes_id'), 'deteccoes', ['id'], unique=False)
    op.create_index(op.f('ix_imagens_id'), 'imagens', ['id'], unique=False)
    op.alter_column('plantas', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index(op.f('ix_pragas_id'), 'pragas', ['id'], unique=False)
    op.create_index(op.f('ix_recomendacoes_id'), 'recomendacoes', ['id'], unique=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               nullable=True)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'senha',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_index(op.f('ix_recomendacoes_id'), table_name='recomendacoes')
    op.drop_index(op.f('ix_pragas_id'), table_name='pragas')
    op.alter_column('plantas', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_index(op.f('ix_imagens_id'), table_name='imagens')
    op.drop_index(op.f('ix_deteccoes_id'), table_name='deteccoes')
    # ### end Alembic commands ###
