"""criando tabelas de verdade

Revision ID: 1fbc48d53a87
Revises: 
Create Date: 2026-03-21 18:19:48.451937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbc48d53a87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doencas_id'), 'doencas', ['id'], unique=False)
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_id'), 'plantas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('url_imagem', sa.Text(), nullable=False),
    sa.Column('data_upload', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_id'), 'imagens', ['id'], unique=False)
    op.create_table('deteccoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=True),
    sa.Column('planta_id', sa.Integer(), nullable=True),
    sa.Column('doenca_id', sa.Integer(), nullable=True),
    sa.Column('porcentagem_confianca', sa.Float(), nullable=True),
    sa.Column('data_deteccao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doenca_id'], ['doencas.id'], ),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagens.id'], ),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deteccoes_id'), 'deteccoes', ['id'], unique=False)
    op.create_table('recomendacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deteccao_id', sa.Integer(), nullable=True),
    sa.Column('texto_recomendacao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deteccao_id'], ['deteccoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendacoes_id'), 'recomendacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recomendacoes_id'), table_name='recomendacoes')
    op.drop_table('recomendacoes')
    op.drop_index(op.f('ix_deteccoes_id'), table_name='deteccoes')
    op.drop_table('deteccoes')
    op.drop_index(op.f('ix_imagens_id'), table_name='imagens')
    op.drop_table('imagens')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_plantas_id'), table_name='plantas')
    op.drop_table('plantas')
    op.drop_index(op.f('ix_doencas_id'), table_name='doencas')
    op.drop_table('doencas')
    # ### end Alembic commands ###
